# Generated by Django 4.2.1 on 2023-05-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='url_id',
            new_name='uuid',
        ),
    ]
