# Generated by Django 4.2.1 on 2023-05-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_url_id_link_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='url',
            new_name='link',
        ),
    ]
